# Generated by Django 5.1.5 on 2025-02-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='block',
            field=models.CharField(choices=[('block1', 'Block 1'), ('block2', 'Block 2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('course1', 'Course 1'), ('course2', 'Course 2')], max_length=10),
        ),
    ]
