# Generated by Django 5.1.5 on 2025-02-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_block_alter_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='block',
            field=models.CharField(choices=[('blockA', 'A'), ('blockB', 'B')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('BEED', 'Bachelor in Elementary Education'), ('BSED', 'Bachelor of Secondary Education'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSIS', 'Bachelor of Science in Information System'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSIT Anim', 'Bachelor of Science in Information Technology with Specialization in Animation'), ('BSCpE', 'Bachelor of Science in Computer Engineering'), ('BSEE', 'Bachelor of Science in Electronics Engineering'), ('BSN', 'Bachelor of Science in Nursing'), ('BSAT', 'Bachelor of Science in Automotive Technology'), ('BSET', 'Bachelor of Science in Electrical Technology'), ('BSEnt', 'Bachelor of Science in Entrepreneurship'), ('BSEt', 'Bachelor of Science in Electronics Technology'), ('BSFT', 'Bachelor of Science in Food Technology'), ('BSMT', 'Bachelor of Science in Mechanical Technology')], max_length=10),
        ),
    ]
