# Generated by Django 5.1.5 on 2025-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_block_alter_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='block',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=10),
        ),
    ]
