# Generated by Django 5.1.5 on 2025-02-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.CharField(choices=[('medical_check', 'Medical Check-up'), ('consultation', 'Consultation'), ('emergency', 'Emergency'), ('follow_up', 'Follow-up Check'), ('medicine', 'Medicine Request'), ('certificate', 'Medical Certificate'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00', '9:00 AM'), ('09:30', '9:30 AM'), ('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 AM'), ('11:30', '11:30 AM'), ('13:00', '1:00 PM'), ('13:30', '1:30 PM'), ('14:00', '2:00 PM'), ('14:30', '2:30 PM'), ('15:00', '3:00 PM'), ('15:30', '3:30 PM'), ('16:00', '4:00 PM')], max_length=5),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='year',
            field=models.CharField(choices=[('1st', 'First Year'), ('2nd', 'Second Year'), ('3rd', 'Third Year'), ('4th', 'Fourth Year')], max_length=3),
        ),
    ]
