# Generated by Django 5.1.5 on 2025-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_contact_no_appointment_home_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='home_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='parent_guardian',
            field=models.CharField(max_length=100),
        ),
    ]
