# Generated by Django 5.1.5 on 2025-02-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_contact_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='types_of_client',
        ),
    ]
